# Generated by Django 5.2.8 on 2025-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the neural network', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the network')),
                ('mode', models.IntegerField(choices=[(1, 'Mode 1 - Single Unparallelized Layer'), (2, 'Mode 2 - Single Parallelized Layer'), (3, 'Mode 3 - Three-Layer Network')], help_text='Generation mode (1, 2, or 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_files_path', models.CharField(blank=True, help_text='Path to cached generated files', max_length=500)),
                ('input_size', models.IntegerField(help_text='Input dimension (N)')),
                ('T', models.IntegerField(help_text='Bit width (e.g., 16 for 16-bit)')),
                ('R', models.BooleanField(default=False, help_text='ReLU activation (True/False)')),
                ('output_size', models.IntegerField(blank=True, help_text='Output dimension (M) - Mode 1 & 2', null=True)),
                ('P', models.IntegerField(default=1, help_text='Parallelism factor (P) - Mode 1 & 2')),
                ('layer_sizes', models.JSONField(blank=True, default=list, help_text='List of layer output sizes [M1, M2, M3] - Mode 3')),
                ('B', models.IntegerField(blank=True, help_text='Multiplier budget (B) - Mode 3', null=True)),
            ],
            options={
                'verbose_name': 'Network Configuration',
                'verbose_name_plural': 'Network Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
