# Generated by Django 6.0 on 2026-01-05 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconfig',
            name='generated_name',
            field=models.CharField(default='', help_text='Auto-generated name based on configuration parameters', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkconfig',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who have created/contributed to this network', related_name='networks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='name',
            field=models.CharField(help_text='User-defined name of the neural network', max_length=255, unique=True),
        ),
    ]
